spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soul-esview?useUnicode=true&characterEncoding=utf8
    password: danjazozumysql1992
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=10)
      time-between-eviction-runs-millis: 18800
      initial-size: 5
server:
  context-path: /esview
  port: 8080
